files:
  - source: /pages/
    translation: /pages/%two_letters_code%/%original_path%/%original_file_name%
  - source: /utils
    translation: /pages/%two_letters_code%/%original_path%/%original_file_name%
